### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by IrynaMukhina** [IrynaMukhina/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Iryyyna** [comment]
Harry James Potter

Harry.Potter@Hogwarts.edu – Hogwarts Owlery – 4 Private Drive Whinging, England

Professional Summary: Extremely powerful Half Blood Wizard looking to utilize my ability to escape death and cast one hell of a patronus spell.

**Comment by IrynaMukhina** [comment]
Thank you, Iryna. Great job!
