### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by IrynaMukhina** [IrynaMukhina/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Iryyyna** [comment]
Harry.Potter@Hogwarts.edu – Hogwarts Owlery – 4 Private Drive Whinging, England

**Comment by IrynaMukhina** [comment]
nice!
