### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by IrynaMukhina** [IrynaMukhina/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Iryyyna** [comment]
Professional Experience:

Head of Auror – Level Two of the Ministry of Magic – 2007 to Present – The Auror Department

Train and establish an elite unit of highly skilled officers. Investigate crimes related to the dark arts. Apprehend and imprison dark wizards/witches.

Student – Hogwarts Schools of Witchcraft and Wizardry – 1991 to 1998 – Relevant School Work

Utilized private lessons received by the Headmaster. Great experience and understanding of the patronus charm (fended off Dementors on multiple occasions). Defense against the dark arts spells: Stunning spell, Disarming spell, Impediment jinx, Full body blind curse, Reductor curse. Curses and Jinxes: Leg lock curse, Furnunculus curse, Knockback jinx, Revulsion jinx, Melofors jinx. Skilled defender against dark creatures such as: Grindylows, Red Caps, Hinkypunks, Boggarts, Erklings, and Dementors.

**Comment by IrynaMukhina** [comment]
it looks great!
