### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by IrynaMukhina** [IrynaMukhina/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Iryyyna** [comment]
Professional Skills: Background in Charms, Healing Magic Expert, Care of Magical Creatures, Wandless Magic, Herbology Knowledge, Potions guru, Transfiguration Skills, Seasoned Duelist, Broomstick Master, Curse/Hex/Jinx, Fluent in Parseltounge, Quidditch Seeker

Education: Hogwarts School of Witchcraft and Wizardry – N.E.W.T Exam in 1998

**Comment by IrynaMukhina** [comment]
Is info about education correct?

**Comment by Iryyyna** [comment]
yes, totally

**Comment by IrynaMukhina** [comment]
thank you
